// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


float temperatura;
float umidita;
int anidride_carbonica;
int diossido_di_azoto;
int etanolo;
int monossido_di_carbonio;
int pm1;
int pm10;
int pm2;
int tvoc;
int voc;

void initProperties(){

  ArduinoCloud.addProperty(temperatura, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(umidita, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(anidride_carbonica, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(diossido_di_azoto, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(etanolo, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(monossido_di_carbonio, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(pm1, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(pm10, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(pm2, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(tvoc, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(voc, READ, ON_CHANGE, NULL, 1);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
